spring:
  application:
    name: user-service
  datasource:
    url: jdbc:postgresql://postgres-user-db:5432/user_db
    username: postgres
    password: password123
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
server:
  port: 9001
eureka:
  client:
    service-url:
      defaultZone: http://discovery-server:8761/eureka/
  instance:
    prefer-ip-address: true

jwt:
  secret: K7vP9mW3qL8tR2nF5xY4jH6dG1cB0zA8sE2uJ9wQ4iT3oM5pN6rV7yX8lZ2kC4eD